### ISSUE TITLE
BUG: Changing the cookie secret is not handled by the client

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/client-web#1652]
**Describe the bug**
Changing the cookie secret in kratos.yml is not handled by the client

**To Reproduce**

1. Start the alkemio stack locally
2. Log in
3. Go to .build/ory/kratos/email-password/kratos.yml
4. Change the cookie secret to:

```yaml
secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE-V2
```
5. Navigate to localhost:3000

You will see 

![image.png](https://images.zenhubusercontent.com/5f227562fdc101c42f08046f/04209ac0-2255-4d48-a813-31b39b6c3713)![image.png](https://images.zenhubusercontent.com/5f227562fdc101c42f08046f/52130dd5-4111-4f12-b112-765794916768)

**Expected behavior**
The cookie is invalidated and a new kratos login flow is initiated.

**Comment by valentinyanakiev** [comment]
The problem seems to manifest because there is no graphql support for oathkeeper reverse proxy-ing. We make requests to configuration query on our graphql endpoint and provide the following authenticator in access-rules.yml:

```yml
  authenticators:
    - handler: cookie_session
    - handler: noop
```

First we try with the cookie_session (for authenticating against operations with guards) and then noop for ones without guards. The problem is, passport returns 401 with cookie_session provided with the wrong cookie_secret and we don't control that flow (it happens before validate is called in the OryStrategy).
